Repository lighttube-org/LightTube, pull requests merged in 2024-01, with the labels that each got.

#114 Fix #111
  LightTube/Contexts/ChannelContext.cs
Labels: bug

#115 [skip ci] Update/Delete outdated documentation/config files
  .github/ISSUE_TEMPLATE/config.yaml
  .gitlab-ci.yml
  CONFIGURATION.md
  OTHERLIBS.md
  README.md
Labels: documentation

#118 Implement Serilog logging
  LightTube/Chores/MigrateDataChore.cs
  LightTube/Chores/QueueChore.cs
  LightTube/Controllers/SettingsController.cs
  LightTube/Database/DatabaseManager.cs
  LightTube/JsCache.cs
  LightTube/LightTube.csproj
  LightTube/Program.cs
Labels: enhancement

#119 Update MongoDB driver for C#
  LightTube/LightTube.csproj
Labels: enhancement
